# Site settings
title: Lanlan Blog
description: Welcome to visit my blog
keywords: Modern, Blogging, Fun
author: Wferr
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site
